name: Merge sample metadata

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      # When someone push to `main` branch
      - main
    paths:
      - 'samples/**/assets/sample.json'

jobs:
  build:
    name: 'Merge all sample.json files to samples.json'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
      - name: Join samples  
        run: |
          jq -s '[.[][]]' ./main/samples/**/assets/sample.json  > ./main/.metadata/samples.json
      - name: Validate JSON
        continue-on-error: true
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./main/templates/metadata-schema.json
          INPUT_JSONS: ./Docs/docs/samples.json
      - name: Commit samples.json to metadata
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./
          branch: main
          add: '.metadata/samples.json'
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}
